networks:
  default:

services:
  app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app/logs:/app/logs
      - ./app/images:/app/images
    networks:
      - default

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app/images:/images
      - ./app/static:/etc/nginx/html
      - ./app/logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./favicon.ico:/images/favicon.ico
    networks:
      - default
    depends_on:
      - app